---
- name: "test netbox prefix module"
  connection: local
  hosts: localhost
  gather_facts: False
  #vars:
  #  ansible_python_interpreter: "/opt/ansible_envs/cloudnetworking/bin/python"
  tasks:
    - name: create prefix
      netbox_prefix:
        netbox_url: http://192.168.28.130/
        netbox_token: edfe7638d4b639632d54900bac5c74a035f344a8
        #validate_certs: False
        data:
          prefix: 1.1.1.0/24
        state: present