---
- hosts: all
 #gather_facts: false
  connection: local
  tasks:
   - name: send configuration commands to IOS
     ios_command:
       commands:
       - show version
       - show interfaces
     register: print_output
   - debug: var=print_output.stdout_lines
